import Fastify from 'fastify';
import cors from '@fastify/cors';
import cookie from '@fastify/cookie';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import { nanoid } from 'nanoid';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.dirname(fileURLToPath(import.meta.url));
const dataFile = path.join(root, 'data.json');
const uploadDir = path.join(root, 'uploads');
fs.mkdirSync(uploadDir, { recursive: true });
const categories = ['camera', 'radio', 'furniture', 'instrument', 'other'];
const roles = ['owner', 'editor', 'viewer'];
const SECRET = process.env.REPAIR_LOG_JWT_SECRET || 'repair-log-local-secret-change-me';
const now = () => new Date().toISOString();
const id = () => nanoid(12);
const initial = () => {
  const owner = { id: 'user-owner', name: '林默', email: 'linmo@example.com', passwordHash: bcrypt.hashSync('repair-log-demo', 10) };
  const household = { id: 'home-demo', name: '默叔的收藏室', createdAt: now() };
  return { users: [owner], households: [household], members: [{ id: id(), householdId: household.id, userId: owner.id, role: 'owner' }], invites: [], items: [], records: [], steps: [], materials: [], damagePoints: [], reminders: [], attachments: [], notifications: [], auditLogs: [] };
};
let db = fs.existsSync(dataFile) ? JSON.parse(fs.readFileSync(dataFile, 'utf8')) : initial();
for (const collection of ['users', 'households', 'members', 'invites', 'items', 'records', 'steps', 'materials', 'damagePoints', 'reminders', 'attachments', 'notifications', 'auditLogs']) if (!Array.isArray(db[collection])) db[collection] = [];
const save = () => fs.writeFileSync(dataFile, JSON.stringify(db, null, 2));
const publicUser = u => ({ id: u.id, name: u.name, email: u.email });
const token = u => jwt.sign({ sub: u.id }, SECRET, { expiresIn: '15m' });
const refreshToken = u => jwt.sign({ sub: u.id, refresh: true }, SECRET, { expiresIn: '30d' });
const fail = (reply, status, code, message, details) => reply.code(status).send({ error: { code, message, ...(details ? { details } : {}) } });

const app = Fastify({ logger: true, bodyLimit: 25 * 1024 * 1024 });
app.addContentTypeParser('application/octet-stream', { parseAs: 'buffer' }, (_, body, done) => done(null, body));
app.addContentTypeParser('*', { parseAs: 'buffer' }, (_, body, done) => done(null, body));
await app.register(cors, { origin: true, credentials: true });
await app.register(cookie);

app.decorateRequest('user', null);
app.decorateRequest('household', null);
app.addHook('preHandler', async (req, reply) => {
  if (req.url.startsWith('/api/v1/auth') || req.url === '/health') return;
  const raw = req.cookies.access_token || (req.headers.authorization || '').replace('Bearer ', '');
  if (!raw) return fail(reply, 401, 'UNAUTHORIZED', '请先登录');
  try { const payload = jwt.verify(raw, SECRET); req.user = db.users.find(u => u.id === payload.sub); } catch { return fail(reply, 401, 'UNAUTHORIZED', '登录已过期'); }
  if (!req.user) return fail(reply, 401, 'UNAUTHORIZED', '用户不存在');
  if (req.url.startsWith('/api/v1/households') || req.url.startsWith('/api/v1/invites')) return;
  const householdId = req.headers['x-household-id'] || db.members.find(m => m.userId === req.user.id)?.householdId;
  const member = db.members.find(m => m.userId === req.user.id && m.householdId === householdId);
  if (!member) return fail(reply, 403, 'FORBIDDEN_HOUSEHOLD', '你不是该家庭成员');
  req.household = { ...db.households.find(h => h.id === householdId), member };
});

app.get('/uploads/*', async (req, reply) => {
  const key = decodeURIComponent(req.params['*'] || '');
  const attachment = db.attachments.find(a => a.fileKey === key && a.householdId === req.household.id);
  if (!attachment) return fail(reply, 404, 'ATTACHMENT_NOT_FOUND', '附件不存在');
  const target = path.resolve(uploadDir, key);
  if (!target.startsWith(`${path.resolve(uploadDir)}${path.sep}`) || !fs.existsSync(target)) return fail(reply, 404, 'ATTACHMENT_NOT_FOUND', '附件不存在');
  return reply.type(attachment.mime || 'application/octet-stream').send(fs.createReadStream(target));
});

app.get('/health', async () => ({ ok: true, service: 'repair-log-api', time: now() }));
app.post('/api/v1/auth/register', async (req, reply) => { const { name, email, password } = req.body || {}; if (!name || !email || !password || password.length < 8) return fail(reply, 400, 'VALIDATION_ERROR', '姓名、邮箱和至少 8 位密码为必填'); if (db.users.some(u => u.email === email)) return fail(reply, 409, 'EMAIL_EXISTS', '邮箱已注册'); const user = { id: id(), name, email, passwordHash: await bcrypt.hash(password, 10) }; const household = { id: id(), name: `${name}的收藏室`, createdAt: now() }; db.users.push(user); db.households.push(household); db.members.push({ id: id(), householdId: household.id, userId: user.id, role: 'owner' }); save(); reply.setCookie('access_token', token(user), { httpOnly: true, sameSite: 'lax', path: '/' }).setCookie('refresh_token', refreshToken(user), { httpOnly: true, sameSite: 'lax', path: '/' }); return reply.code(201).send({ user: publicUser(user), household }); });
app.post('/api/v1/auth/login', async (req, reply) => { const { email, password } = req.body || {}; const user = db.users.find(u => u.email === email); if (!user || !(await bcrypt.compare(password || '', user.passwordHash))) return fail(reply, 401, 'INVALID_CREDENTIALS', '邮箱或密码错误'); reply.setCookie('access_token', token(user), { httpOnly: true, sameSite: 'lax', path: '/' }).setCookie('refresh_token', refreshToken(user), { httpOnly: true, sameSite: 'lax', path: '/' }); return { user: publicUser(user) }; });
app.post('/api/v1/auth/refresh', async (req, reply) => { try { const p = jwt.verify(req.cookies.refresh_token || '', SECRET); if (!p.refresh) throw Error(); const user = db.users.find(u => u.id === p.sub); if (!user) throw Error(); reply.setCookie('access_token', token(user), { httpOnly: true, sameSite: 'lax', path: '/' }); return { ok: true }; } catch { return fail(reply, 401, 'REFRESH_EXPIRED', '请重新登录'); } });
app.post('/api/v1/auth/logout', async (_, reply) => { reply.clearCookie('access_token', { path: '/' }).clearCookie('refresh_token', { path: '/' }); return { ok: true }; });
app.get('/api/v1/me', async req => ({ user: publicUser(req.user), households: db.members.filter(m => m.userId === req.user.id).map(m => ({ ...db.households.find(h => h.id === m.householdId), role: m.role })) }));

app.get('/api/v1/households', async req => db.members.filter(m => m.userId === req.user.id).map(m => ({ ...db.households.find(h => h.id === m.householdId), role: m.role })));
app.post('/api/v1/households', async (req, reply) => { const { name } = req.body || {}; if (!name) return fail(reply, 400, 'VALIDATION_ERROR', '家庭名称不能为空'); const h = { id: id(), name, createdAt: now() }; db.households.push(h); db.members.push({ id: id(), householdId: h.id, userId: req.user.id, role: 'owner' }); save(); return reply.code(201).send(h); });
app.get('/api/v1/households/:hid/members', async (req, reply) => { const h = db.households.find(x => x.id === req.params.hid); if (!h) return fail(reply, 404, 'HOUSEHOLD_NOT_FOUND', '家庭不存在'); const member = db.members.find(m => m.householdId === h.id && m.userId === req.user.id); if (!member) return fail(reply, 403, 'FORBIDDEN_HOUSEHOLD', '无权访问'); return db.members.filter(m => m.householdId === h.id).map(m => ({ ...publicUser(db.users.find(u => u.id === m.userId)), role: m.role })); });
app.patch('/api/v1/households/:hid/members/:uid', async (req, reply) => { const owner = db.members.find(m => m.householdId === req.params.hid && m.userId === req.user.id); if (!owner || owner.role !== 'owner') return fail(reply, 403, 'FORBIDDEN_ROLE', '仅所有者可修改成员'); const member = db.members.find(m => m.householdId === req.params.hid && m.userId === req.params.uid); if (!member) return fail(reply, 404, 'MEMBER_NOT_FOUND', '成员不存在'); if (!roles.includes(req.body?.role) || req.body.role === 'owner' || member.role === 'owner') return fail(reply, 400, 'INVALID_ROLE', '角色无效，所有者不可被直接转移'); member.role = req.body.role; save(); return { ...publicUser(db.users.find(u => u.id === member.userId)), role: member.role }; });
app.delete('/api/v1/households/:hid/members/:uid', async (req, reply) => { const owner = db.members.find(m => m.householdId === req.params.hid && m.userId === req.user.id); if (!owner || owner.role !== 'owner') return fail(reply, 403, 'FORBIDDEN_ROLE', '仅所有者可移除成员'); const index = db.members.findIndex(m => m.householdId === req.params.hid && m.userId === req.params.uid && m.role !== 'owner'); if (index < 0) return fail(reply, 404, 'MEMBER_NOT_FOUND', '成员不存在或不可移除所有者'); db.members.splice(index, 1); save(); return { ok: true }; });
app.post('/api/v1/households/:hid/invites', async (req, reply) => { const m = db.members.find(x => x.householdId === req.params.hid && x.userId === req.user.id); if (!m || m.role !== 'owner') return fail(reply, 403, 'FORBIDDEN_ROLE', '仅所有者可邀请成员'); const role = req.body?.role || 'editor'; if (!roles.includes(role) || role === 'owner') return fail(reply, 400, 'INVALID_ROLE', '邀请角色只能是 editor 或 viewer'); const invite = { id: id(), code: nanoid(18), householdId: req.params.hid, role, createdBy: req.user.id, expiresAt: new Date(Date.now() + 7 * 864e5).toISOString(), usedAt: null }; db.invites.push(invite); save(); return { code: invite.code, expiresAt: invite.expiresAt, role: invite.role }; });
app.post('/api/v1/invites/:code/accept', async (req, reply) => { const invite = db.invites.find(x => x.code === req.params.code && !x.usedAt && new Date(x.expiresAt).getTime() > Date.now()); if (!invite) return fail(reply, 404, 'INVITE_NOT_FOUND', '邀请码无效或已过期'); const h = db.households.find(x => x.id === invite.householdId); if (!h) return fail(reply, 404, 'HOUSEHOLD_NOT_FOUND', '家庭不存在'); const existing = db.members.find(m => m.householdId === h.id && m.userId === req.user.id); if (!existing) db.members.push({ id: id(), householdId: h.id, userId: req.user.id, role: invite.role }); invite.usedAt = now(); save(); return h; });

function requireRole(req, reply, allowed = ['owner', 'editor']) { if (!allowed.includes(req.household.member.role)) { fail(reply, 403, 'FORBIDDEN_ROLE', '当前角色无写入权限'); return false; } return true; }
function itemView(item) { const records = db.records.filter(r => r.itemId === item.id && !r.deletedAt); const materials = db.materials.filter(m => records.some(r => r.id === m.recordId)); return { ...item, recordsCount: records.length, totalCost: records.reduce((sum, r) => sum + Number(r.laborCost || 0), 0) + materials.reduce((sum, m) => sum + Number(m.totalCost || 0), 0), latestRecord: records.sort((a,b) => b.startedAt.localeCompare(a.startedAt))[0] || null }; }
app.get('/api/v1/items', async req => { const { category, q, tag, archived = 'false', page = 1, size = 20 } = req.query || {}; let data = db.items.filter(i => i.householdId === req.household.id && i.archived === (archived === 'true')); if (category) data = data.filter(i => i.category === category); if (q) data = data.filter(i => `${i.name} ${i.brand} ${i.model} ${(i.tags || []).join(' ')}`.toLowerCase().includes(String(q).toLowerCase())); if (tag) data = data.filter(i => (i.tags || []).includes(tag)); const p = Math.max(1, Number(page)), s = Math.min(100, Math.max(1, Number(size))); return { data: data.slice((p - 1) * s, p * s).map(itemView), page: p, size: s, total: data.length }; });
app.post('/api/v1/items', async (req, reply) => { if (!requireRole(req, reply)) return; const b = req.body || {}; if (!b.name || !categories.includes(b.category || 'other')) return fail(reply, 400, 'VALIDATION_ERROR', '名称和有效类别为必填'); const item = { id: id(), householdId: req.household.id, name: b.name, category: b.category, brand: b.brand || '', model: b.model || '', yearMade: b.yearMade || null, acquiredAt: b.acquiredAt || null, acquiredFrom: b.acquiredFrom || '', condition: b.condition || 'good', description: b.description || '', tags: b.tags || [], archived: false, createdAt: now(), createdBy: req.user.id }; db.items.push(item); db.auditLogs.push({ id: id(), householdId: req.household.id, userId: req.user.id, action: 'item.created', targetId: item.id, at: now() }); save(); return reply.code(201).send(itemView(item)); });
app.get('/api/v1/items/:id', async (req, reply) => { const item = db.items.find(i => i.id === req.params.id && i.householdId === req.household.id); if (!item) return fail(reply, 404, 'ITEM_NOT_FOUND', '物件不存在'); return { ...itemView(item), damagePoints: db.damagePoints.filter(d => d.itemId === item.id), records: db.records.filter(r => r.itemId === item.id && !r.deletedAt).sort((a,b) => b.startedAt.localeCompare(a.startedAt)).slice(0, 5), reminders: db.reminders.filter(r => r.itemId === item.id) }; });
app.patch('/api/v1/items/:id', async (req, reply) => { if (!requireRole(req, reply)) return; const item = db.items.find(i => i.id === req.params.id && i.householdId === req.household.id); if (!item) return fail(reply, 404, 'ITEM_NOT_FOUND', '物件不存在'); const b = req.body || {}; if (b.category !== undefined && !categories.includes(b.category)) return fail(reply, 400, 'VALIDATION_ERROR', '类别无效'); const allowed = ['name', 'category', 'brand', 'model', 'yearMade', 'acquiredAt', 'acquiredFrom', 'condition', 'description', 'tags', 'coverAttachmentId']; for (const key of allowed) if (Object.prototype.hasOwnProperty.call(b, key)) item[key] = b[key]; item.updatedAt = now(); save(); return itemView(item); });
app.post('/api/v1/items/:id/archive', async (req, reply) => { if (!requireRole(req, reply)) return; const item = db.items.find(i => i.id === req.params.id && i.householdId === req.household.id); if (!item) return fail(reply, 404, 'ITEM_NOT_FOUND', '物件不存在'); item.archived = true; item.archivedAt = now(); save(); return item; });

app.get('/api/v1/items/:id/damage-points', async (req, reply) => { const item = db.items.find(i => i.id === req.params.id && i.householdId === req.household.id); if (!item) return fail(reply, 404, 'ITEM_NOT_FOUND', '物件不存在'); return db.damagePoints.filter(d => d.itemId === item.id); });
app.post('/api/v1/items/:id/damage-points', async (req, reply) => { if (!requireRole(req, reply)) return; const item = db.items.find(i => i.id === req.params.id && i.householdId === req.household.id); if (!item) return fail(reply, 404, 'ITEM_NOT_FOUND', '物件不存在'); const b = req.body || {}; const d = { id: id(), itemId: item.id, name: b.name || b.label || '', region: b.region || null, description: b.description || '', status: b.status || 'open', severity: b.severity || null, firstNoticedAt: b.firstNoticedAt || null, x: b.x ?? null, y: b.y ?? null, createdAt: now() }; db.damagePoints.push(d); save(); return reply.code(201).send(d); });
app.patch('/api/v1/damage-points/:id', async (req, reply) => { if (!requireRole(req, reply)) return; const d = db.damagePoints.find(x => x.id === req.params.id); const item = d && db.items.find(i => i.id === d.itemId && i.householdId === req.household.id); if (!d || !item) return fail(reply, 404, 'DAMAGE_POINT_NOT_FOUND', '损坏部位不存在'); for (const key of ['name', 'label', 'region', 'description', 'status', 'severity', 'firstNoticedAt', 'x', 'y']) if (Object.prototype.hasOwnProperty.call(req.body || {}, key)) d[key] = req.body[key]; d.updatedAt = now(); save(); return d; });

function recordView(r) { const steps = db.steps.filter(s => s.recordId === r.id).sort((a,b) => a.order - b.order); const stepIds = new Set(steps.map(s => s.id)); return { ...r, steps, materials: db.materials.filter(m => m.recordId === r.id), attachments: db.attachments.filter(a => a.householdId === r.householdId && ((a.ownerType === 'record' && a.ownerId === r.id) || (a.ownerType === 'step' && stepIds.has(a.ownerId)))) }; }
app.get('/api/v1/items/:id/records', async (req, reply) => { const item = db.items.find(i => i.id === req.params.id && i.householdId === req.household.id); if (!item) return fail(reply, 404, 'ITEM_NOT_FOUND', '物件不存在'); return db.records.filter(r => r.itemId === item.id && !r.deletedAt).sort((a,b) => b.startedAt.localeCompare(a.startedAt)).map(recordView); });
app.post('/api/v1/items/:id/records', async (req, reply) => { if (!requireRole(req, reply)) return; const item = db.items.find(i => i.id === req.params.id && i.householdId === req.household.id); if (!item) return fail(reply, 404, 'ITEM_NOT_FOUND', '物件不存在'); const b = req.body || {}; if (!b.title) return fail(reply, 400, 'VALIDATION_ERROR', '履历标题不能为空'); if (b.steps !== undefined && !Array.isArray(b.steps) || b.materials !== undefined && !Array.isArray(b.materials)) return fail(reply, 400, 'VALIDATION_ERROR', '步骤和材料必须是数组'); const r = { id: id(), householdId: req.household.id, itemId: item.id, type: b.type || 'repair', title: b.title, diagnosis: b.diagnosis || '', startedAt: b.startedAt || now(), finishedAt: b.finishedAt || null, performedBy: b.performedBy || 'self', shopName: b.shopName || '', laborCost: Number(b.laborCost || 0), result: b.result || 'observing', notes: b.notes || '', createdBy: req.user.id, createdAt: now(), status: b.status || 'draft' }; db.records.push(r); replaceChildren(r.id, b.steps, b.materials); save(); return reply.code(201).send(recordView(r)); });
app.get('/api/v1/records/:id', async (req, reply) => { const r = db.records.find(x => x.id === req.params.id && x.householdId === req.household.id && !x.deletedAt); if (!r) return fail(reply, 404, 'RECORD_NOT_FOUND', '履历不存在'); return recordView(r); });
app.patch('/api/v1/records/:id', async (req, reply) => { if (!requireRole(req, reply)) return; const r = db.records.find(x => x.id === req.params.id && x.householdId === req.household.id && !x.deletedAt); if (!r) return fail(reply, 404, 'RECORD_NOT_FOUND', '履历不存在'); const b = req.body || {}; const allowed = ['type', 'title', 'diagnosis', 'startedAt', 'finishedAt', 'performedBy', 'shopName', 'shopContact', 'laborCost', 'result', 'notes', 'status']; for (const key of allowed) if (Object.prototype.hasOwnProperty.call(b, key)) r[key] = b[key]; r.updatedAt = now(); if (b.steps !== undefined || b.materials !== undefined) replaceChildren(r.id, b.steps || db.steps.filter(s => s.recordId === r.id), b.materials || db.materials.filter(m => m.recordId === r.id)); save(); return recordView(r); });
app.delete('/api/v1/records/:id', async (req, reply) => { if (!requireRole(req, reply)) return; const r = db.records.find(x => x.id === req.params.id && x.householdId === req.household.id); if (!r) return fail(reply, 404, 'RECORD_NOT_FOUND', '履历不存在'); r.deletedAt = now(); save(); return { ok: true, recoverUntil: new Date(Date.now() + 30 * 864e5).toISOString() }; });
app.get('/api/v1/items/:id/stats', async (req, reply) => { const item = db.items.find(i => i.id === req.params.id && i.householdId === req.household.id); if (!item) return fail(reply, 404, 'ITEM_NOT_FOUND', '物件不存在'); const rs = db.records.filter(r => r.itemId === item.id && !r.deletedAt); const ms = db.materials.filter(m => rs.some(r => r.id === m.recordId)); return { repairCount: rs.length, totalCost: rs.reduce((n, r) => n + Number(r.laborCost || 0), 0) + ms.reduce((n, m) => n + Number(m.totalCost || 0), 0), materialTop5: Object.entries(ms.reduce((a, m) => { a[m.name] = (a[m.name] || 0) + Number(m.totalCost || 0); return a; }, {})).sort((a,b) => b[1]-a[1]).slice(0, 5).map(([name, totalCost]) => ({ name, totalCost })) }; });
app.get('/api/v1/items/:id/export', async (req, reply) => { const item = db.items.find(i => i.id === req.params.id && i.householdId === req.household.id); if (!item) return fail(reply, 404, 'ITEM_NOT_FOUND', '物件不存在'); const payload = { exportedAt: now(), item, damagePoints: db.damagePoints.filter(d => d.itemId === item.id), records: db.records.filter(r => r.itemId === item.id && !r.deletedAt).map(recordView), reminders: db.reminders.filter(r => r.itemId === item.id) }; reply.header('content-disposition', `attachment; filename="repair-log-${item.id}.json"`); return payload; });
function replaceChildren(recordId, steps = [], materials = []) { db.steps = db.steps.filter(s => s.recordId !== recordId); db.materials = db.materials.filter(m => m.recordId !== recordId); (steps || []).forEach((s, i) => db.steps.push({ id: id(), recordId, order: i + 1, content: s.content, durationMin: s.durationMin || null, attachmentIds: s.attachmentIds || [] })); (materials || []).forEach(m => { const quantity = Number(m.quantity || 1); const unitPrice = Number(m.unitPrice || 0); db.materials.push({ id: id(), recordId, name: m.name, spec: m.spec || '', quantity, unit: m.unit || '件', unitPrice, totalCost: Number(m.totalCost ?? unitPrice * quantity), source: m.source || '', note: m.note || '' }); }); }

function ownerBelongsToHousehold(ownerType, ownerId, householdId) {
  if (!ownerType || !ownerId) return false;
  if (ownerType === 'item') return db.items.some(x => x.id === ownerId && x.householdId === householdId);
  if (ownerType === 'record') return db.records.some(x => x.id === ownerId && x.householdId === householdId && !x.deletedAt);
  if (ownerType === 'step') return db.steps.some(x => x.id === ownerId && db.records.some(r => r.id === x.recordId && r.householdId === householdId && !r.deletedAt));
  return false;
}
app.post('/api/v1/attachments/presign', async (req, reply) => { if (!requireRole(req, reply)) return; const { filename, mime, size, ownerType, ownerId, phase } = req.body || {}; const bytes = Number(size); if (!filename || !mime || !Number.isFinite(bytes) || bytes <= 0 || bytes > 20 * 1024 * 1024) return fail(reply, 400, 'FILE_TOO_LARGE', '附件不能为空且不能超过 20MB'); if (!ownerBelongsToHousehold(ownerType, ownerId, req.household.id)) return fail(reply, 400, 'INVALID_OWNER', '附件归属对象不存在'); const fileKey = `${req.household.id}/${id()}-${path.basename(filename)}`; return { uploadUrl: `/api/v1/attachments/upload/${encodeURIComponent(fileKey)}`, fileKey, expiresIn: 900, ownerType, ownerId, phase, mime }; });
app.put('/api/v1/attachments/upload/*', async (req, reply) => { const key = decodeURIComponent(req.params['*'] || ''); const target = path.resolve(uploadDir, key); const body = Buffer.isBuffer(req.body) ? req.body : Buffer.from(req.body || ''); if (!target.startsWith(`${path.resolve(uploadDir)}${path.sep}`)) return fail(reply, 400, 'INVALID_FILE_KEY', '文件路径无效'); if (key.split('/')[0] !== req.household.id) return fail(reply, 403, 'FORBIDDEN_HOUSEHOLD', '无权上传到该家庭'); if (body.length > 20 * 1024 * 1024) return fail(reply, 413, 'FILE_TOO_LARGE', '附件不能超过 20MB'); fs.mkdirSync(path.dirname(target), { recursive: true }); fs.writeFileSync(target, body); return { ok: true }; });
app.post('/api/v1/attachments/complete', async (req, reply) => { if (!requireRole(req, reply)) return; const b = req.body || {}; if (!b.fileKey || typeof b.fileKey !== 'string' || b.fileKey.split('/')[0] !== req.household.id) return fail(reply, 400, 'INVALID_FILE_KEY', '文件路径无效'); if (!ownerBelongsToHousehold(b.ownerType, b.ownerId, req.household.id)) return fail(reply, 400, 'INVALID_OWNER', '附件归属对象不存在'); const target = path.resolve(uploadDir, b.fileKey); if (!target.startsWith(`${path.resolve(uploadDir)}${path.sep}`) || !fs.existsSync(target)) return fail(reply, 400, 'UPLOAD_NOT_FOUND', '请先上传文件'); const a = { id: id(), householdId: req.household.id, ownerType: b.ownerType, ownerId: b.ownerId, phase: b.phase || 'doc', fileKey: b.fileKey, mime: b.mime || 'application/octet-stream', size: Number(b.size || fs.statSync(target).size), caption: b.caption || '', takenAt: b.takenAt || null, createdAt: now() }; db.attachments.push(a); save(); return reply.code(201).send({ ...a, url: `/uploads/${a.fileKey}` }); });
app.get('/api/v1/attachments/:id/url', async (req, reply) => { const a = db.attachments.find(x => x.id === req.params.id && x.householdId === req.household.id); if (!a) return fail(reply, 404, 'ATTACHMENT_NOT_FOUND', '附件不存在'); return { url: `/uploads/${a.fileKey}`, expiresIn: 900 }; });
app.patch('/api/v1/attachments/:id', async (req, reply) => { if (!requireRole(req, reply)) return; const a = db.attachments.find(x => x.id === req.params.id && x.householdId === req.household.id); if (!a) return fail(reply, 404, 'ATTACHMENT_NOT_FOUND', '附件不存在'); for (const key of ['caption', 'phase']) if (Object.prototype.hasOwnProperty.call(req.body || {}, key)) a[key] = req.body[key]; save(); return a; });
app.delete('/api/v1/attachments/:id', async (req, reply) => { if (!requireRole(req, reply)) return; const i = db.attachments.findIndex(x => x.id === req.params.id && x.householdId === req.household.id); if (i < 0) return fail(reply, 404, 'ATTACHMENT_NOT_FOUND', '附件不存在'); db.attachments.splice(i, 1); save(); return { ok: true }; });

app.get('/api/v1/reminders', async req => { const { status } = req.query || {}; return db.reminders.filter(r => r.householdId === req.household.id && (!status || r.status === status)).sort((a,b) => a.nextFireAt.localeCompare(b.nextFireAt)); });
const validReminderRule = rule => ['once', 'monthly', 'quarterly', 'yearly'].includes(rule) || /^every_\d+_days$/.test(rule);
app.post('/api/v1/items/:id/reminders', async (req, reply) => { if (!requireRole(req, reply)) return; const item = db.items.find(x => x.id === req.params.id && x.householdId === req.household.id); if (!item) return fail(reply, 404, 'ITEM_NOT_FOUND', '物件不存在'); const b = req.body || {}; const rule = b.rule || 'once'; if (!b.title || !validReminderRule(rule)) return fail(reply, 400, 'VALIDATION_ERROR', '提醒标题和规则无效'); const r = { id: id(), householdId: req.household.id, itemId: item.id, title: b.title, rule, nextFireAt: b.nextFireAt || now(), channels: b.channels || ['in_app'], status: 'active', autoCreateRecord: b.autoCreateRecord !== false, createdAt: now() }; db.reminders.push(r); save(); return reply.code(201).send(r); });
app.patch('/api/v1/reminders/:id', async (req, reply) => { if (!requireRole(req, reply)) return; const r = db.reminders.find(x => x.id === req.params.id && x.householdId === req.household.id); if (!r) return fail(reply, 404, 'REMINDER_NOT_FOUND', '提醒不存在'); const b = req.body || {}; if (b.rule !== undefined && !validReminderRule(b.rule)) return fail(reply, 400, 'VALIDATION_ERROR', '提醒规则无效'); for (const key of ['title', 'rule', 'nextFireAt', 'channels', 'status', 'autoCreateRecord']) if (Object.prototype.hasOwnProperty.call(b, key)) r[key] = b[key]; r.updatedAt = now(); save(); return r; });
app.post('/api/v1/reminders/:id/complete', async (req, reply) => { if (!requireRole(req, reply)) return; const r = db.reminders.find(x => x.id === req.params.id && x.householdId === req.household.id); if (!r) return fail(reply, 404, 'REMINDER_NOT_FOUND', '提醒不存在'); const item = db.items.find(x => x.id === r.itemId && x.householdId === req.household.id); if (!item) return fail(reply, 404, 'ITEM_NOT_FOUND', '物件不存在'); r.status = 'done'; r.completedAt = now(); let record = null; if (req.body?.createRecord !== false && r.autoCreateRecord) { record = { id: id(), householdId: r.householdId, itemId: r.itemId, type: 'maintenance', title: r.title, diagnosis: '', startedAt: now(), finishedAt: now(), performedBy: 'self', laborCost: 0, result: 'fixed', notes: '由提醒完成自动生成', createdBy: req.user.id, createdAt: now(), status: 'published' }; db.records.push(record); } save(); return { reminder: r, record: record && recordView(record) }; });
app.post('/api/v1/reminders/:id/snooze', async (req, reply) => { if (!requireRole(req, reply)) return; const r = db.reminders.find(x => x.id === req.params.id && x.householdId === req.household.id); if (!r) return fail(reply, 404, 'REMINDER_NOT_FOUND', '提醒不存在'); r.nextFireAt = new Date(Date.now() + Number(req.body?.days || 1) * 864e5).toISOString(); save(); return r; });
app.get('/api/v1/notifications', async req => db.notifications.filter(n => n.householdId === req.household.id).sort((a,b) => b.createdAt.localeCompare(a.createdAt)));
app.get('/api/v1/audit-logs', async req => db.auditLogs.filter(l => l.householdId === req.household.id).sort((a,b) => b.at.localeCompare(a.at)));

async function scanReminders() { const current = Date.now(); for (const reminder of db.reminders.filter(r => r.status === 'active' && new Date(r.nextFireAt).getTime() <= current)) { db.notifications.push({ id: id(), householdId: reminder.householdId, userId: null, type: 'reminder.due', title: reminder.title, reminderId: reminder.id, createdAt: now(), readAt: null }); if (reminder.rule === 'once') reminder.status = 'done'; else { const days = reminder.rule === 'monthly' ? 30 : reminder.rule === 'quarterly' ? 90 : reminder.rule === 'yearly' ? 365 : Number(reminder.rule.match(/every_(\d+)_days/)?.[1] || 30); reminder.nextFireAt = new Date(Date.now() + days * 864e5).toISOString(); } } save(); }
const reminderTimer = setInterval(scanReminders, 60 * 60 * 1000);
reminderTimer.unref?.();

const port = Number(process.env.PORT || 8787);
app.listen({ port, host: '0.0.0.0' }).then(() => console.log(`Repair Log API listening on http://localhost:${port}`));
