import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Archive, Bell, BookOpen, CalendarDays, Camera, Check, ChevronRight, CircleUserRound, Clock3, FileDown, Filter, Home, Image as ImageIcon, LayoutGrid, MoreHorizontal, Plus, Search, Settings, Share2, Tag, Wrench, X } from 'lucide-react';
import './styles.css';
import './compare.css';
import { api } from './lib/api';

type Category = '相机' | '收音机' | '家具' | '乐器' | '其他';
type Item = { id:number; name:string; category:Category; meta:string; condition:string; image:string; tags:string[]; last:string; cost:number; records:number };
type RecordItem = { id:number; title:string; type:string; date:string; result:string; body:string; cost:number; photos:string[]; createdBy:string };

const seedItems: Item[] = [
  { id:1, name:'海鸥 4A 双反', category:'相机', meta:'海鸥 · 4A', condition:'良好', image:'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=900&q=80', tags:['胶片','收藏'], last:'2025-08-14', cost:268, records:4 },
  { id:2, name:'飞利浦 B5X43A 收音机', category:'收音机', meta:'Philips · B5X43A', condition:'一般', image:'https://images.unsplash.com/photo-1584905066893-7d5c0c85eab7?auto=format&fit=crop&w=900&q=80', tags:['电子管','客厅'], last:'2025-05-22', cost:420, records:2 },
  { id:3, name:'Yamaha FG-180', category:'乐器', meta:'Yamaha · FG-180', condition:'良好', image:'https://images.unsplash.com/photo-1525201548942-d8732f6617a0?auto=format&fit=crop&w=900&q=80', tags:['木吉他','日常使用'], last:'2025-07-03', cost:156, records:3 },
  { id:4, name:'樱桃木五斗柜', category:'家具', meta:'手工制作 · 约 1980', condition:'良好', image:'https://images.unsplash.com/photo-1594026112284-02bb6f3352fe?auto=format&fit=crop&w=900&q=80', tags:['木作','家传'], last:'2024-11-18', cost:96, records:1 },
  { id:5, name:'Sony WM-2 随身听', category:'其他', meta:'Sony · WM-2', condition:'待修', image:'https://images.unsplash.com/photo-1585771724684-38269d6639fd?auto=format&fit=crop&w=900&q=80', tags:['磁带','电子'], last:'2024-09-09', cost:0, records:0 },
];
const seedRecords: Record<number, RecordItem[]> = {
  1:[{id:11,title:'更换取景器遮光海绵',type:'维修',date:'2025-08-14',result:'已修复',body:'密封海绵老化导致进潮，取景器出现雾气。',cost:58,photos:['https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=300&q=70'],createdBy:'林默'},{id:12,title:'全机清洁与润滑',type:'保养',date:'2025-02-20',result:'已完成',body:'快门、过片机构清洁并重新上油。',cost:30,photos:[],createdBy:'林默'}],
  2:[{id:21,title:'更换电解电容',type:'维修',date:'2025-05-22',result:'已修复',body:'更换 6 只老化电容，消除交流声。',cost:260,photos:['https://images.unsplash.com/photo-1584905066893-7d5c0c85eab7?auto=format&fit=crop&w=300&q=70'],createdBy:'陈叔'}],
  3:[{id:31,title:'换弦并上指板油',type:'保养',date:'2025-07-03',result:'已完成',body:'更换 D’Addario 11-52，指板深度清洁。',cost:86,photos:[],createdBy:'林默'}],
  4:[{id:41,title:'修复左侧抽屉滑轨',type:'维修',date:'2024-11-18',result:'已修复',body:'重做榫头并更换黄铜滑轨。',cost:96,photos:[],createdBy:'陈叔'}],
  5:[]
};

const categoryIcons:Record<Category, string> = { 相机:'◉', 收音机:'◌', 家具:'⌂', 乐器:'♫', 其他:'◇' };
const categoryMap: Record<string, Category> = { camera:'相机', radio:'收音机', furniture:'家具', instrument:'乐器', other:'其他' };
const categoryApiMap: Record<Category, string> = { 相机:'camera', 收音机:'radio', 家具:'furniture', 乐器:'instrument', 其他:'other' };
function App(){
  const [page,setPage]=useState<'items'|'reminders'|'household'|'settings'>('items');
  const [items,setItems]=useState(seedItems); const [selected,setSelected]=useState<Item|null>(null);
  const [records,setRecords]=useState(seedRecords); const [query,setQuery]=useState(''); const [category,setCategory]=useState<Category|'全部'>('全部');
  const [showNew,setShowNew]=useState(false); const [showRecord,setShowRecord]=useState(false); const [toast,setToast]=useState('');
  const [apiOnline,setApiOnline]=useState(false);
  useEffect(() => { let alive = true; api.login('linmo@example.com', 'repair-log-demo').then(() => api.items()).then(result => { if (!alive) return; setApiOnline(true); if (!result.data.length) return; const remote = result.data.map((i: any) => ({ id: i.id, name: i.name, category: categoryMap[i.category] || '其他', meta: [i.brand, i.model].filter(Boolean).join(' · ') || '待补充品牌与型号', condition: ({ excellent:'极佳', good:'良好', fair:'一般', broken:'待修' } as any)[i.condition] || i.condition, image: i.coverUrl || seedItems[0].image, tags: i.tags || [], last: i.latestRecord?.startedAt?.slice(0,10) || '尚无记录', cost: i.totalCost || 0, records: i.recordsCount || 0 })); setItems(remote); }).catch(() => undefined); return () => { alive = false; }; }, []);
  const filtered=useMemo(()=>items.filter(i=>(category==='全部'||i.category===category)&&(!query||`${i.name}${i.meta}${i.tags.join('')}`.toLowerCase().includes(query.toLowerCase()))),[items,category,query]);
  const notify=(s:string)=>{setToast(s);setTimeout(()=>setToast(''),2500)};
  const addItem=(name:string,cat:Category)=>{const localId=Date.now();const localItem={id:localId,name,category:cat,meta:'待补充品牌与型号',condition:'良好',image:'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=900&q=80',tags:[],last:'尚无记录',cost:0,records:0};setItems([localItem,...items]);setRecords({...records,[localId]:[]});setShowNew(false);if(apiOnline) api.createItem({name,category:categoryApiMap[cat],condition:'good'}).then((remote:any)=>{setItems(current=>current.map(i=>i.id===localId?{...i,id:remote.id}:i));setRecords(current=>{const next={...current};next[remote.id]=next[localId]||[];delete next[localId];return next;});notify('物件档案已同步');}).catch(()=>notify('物件已保存到本地'));else notify('物件档案已创建');};
  const addRecord=(title:string)=>{if(!selected)return;const localRecord={id:Date.now(),title,type:'维修',date:new Date().toISOString().slice(0,10),result:'草稿',body:'记录诊断和处理过程…',cost:0,photos:[],createdBy:'我'};setRecords({...records,[selected.id]:[localRecord,...(records[selected.id]||[])]});setItems(items.map(i=>i.id===selected.id?{...i,records:i.records+1,last:localRecord.date}:i));setShowRecord(false);if(apiOnline && typeof selected.id==='string') api.createRecord(selected.id,{title,status:'draft',type:'repair'}).then(()=>notify('维修履历已同步')).catch(()=>notify('履历已保存到本地'));else notify('维修履历已保存');};
  return <div className="app"><aside className="sidebar"><div className="brand"><div className="brand-mark"><Wrench size={18}/></div><div><strong>旧物维修履历</strong><span>REPAIR LOG</span></div></div><div className="space-switch"><div className="avatar">林</div><div><small>当前家庭空间</small><b>默叔的收藏室</b></div><ChevronRight size={16}/></div><nav><button className={page==='items'?'active':''} onClick={()=>{setPage('items');setSelected(null)}}><LayoutGrid size={18}/>物件档案<span className="count">{items.length}</span></button><button className={page==='reminders'?'active':''} onClick={()=>setPage('reminders')}><Bell size={18}/>提醒中心<span className="dot"></span></button><button className={page==='household'?'active':''} onClick={()=>setPage('household')}><Home size={18}/>家庭成员</button></nav><div className="sidebar-bottom"><button onClick={()=>setPage('settings')}><Settings size={18}/>设置</button><div className="user"><div className="avatar small">林</div><div><b>林默</b><small>所有者</small></div><MoreHorizontal size={17}/></div></div></aside>
    <main className="main">{page==='items'&&!selected&&<><header className="topbar"><div><p className="eyebrow">我的档案库</p><h1>物件档案</h1></div><div className="top-actions"><button className="icon-btn" title="通知"><Bell size={19}/><i></i></button><button className="primary" onClick={()=>setShowNew(true)}><Plus size={17}/>添加物件</button></div></header><section className="stats"><div><span>物件总数</span><strong>{items.length}</strong><em>+1 本月</em></div><div><span>本年维修</span><strong>12</strong><em>+3 较去年</em></div><div><span>累计花费</span><strong>¥1,248</strong><em>含材料与工时</em></div><div><span>待处理提醒</span><strong>3</strong><em className="warn">需要关注</em></div></section><div className="toolbar"><div className="search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索物件、品牌或标签"/></div><div className="filters"><Filter size={16}/>{(['全部','相机','收音机','家具','乐器','其他'] as const).map(c=><button key={c} className={category===c?'selected':''} onClick={()=>setCategory(c)}>{c}{c!=='全部'&&<small>{items.filter(i=>i.category===c).length}</small>}</button>)}</div><button className="view-btn" title="切换视图"><LayoutGrid size={17}/></button></div><section className="section-head"><div><h2>全部物件</h2><span>{filtered.length} 件档案</span></div><button className="text-btn"><Archive size={15}/>查看已归档</button></section><div className="grid">{filtered.map(item=><ItemCard key={item.id} item={item} onClick={()=>setSelected(item)}/>) }<button className="add-card" onClick={()=>setShowNew(true)}><div><Plus size={24}/></div><strong>添加一件新物件</strong><span>建立属于它的第一份档案</span></button></div></>}
    {page==='items'&&selected&&<ItemDetail item={selected} records={records[selected.id]||[]} onBack={()=>setSelected(null)} onAdd={()=>setShowRecord(true)} />}
    {page==='reminders'&&<Reminders notify={notify}/>} {page==='household'&&<Household notify={notify}/>} {page==='settings'&&<SettingsPage notify={notify}/>}</main>
    {showNew&&<NewItemModal onClose={()=>setShowNew(false)} onCreate={addItem}/>} {showRecord&&<NewRecordModal onClose={()=>setShowRecord(false)} onCreate={addRecord}/>} {toast&&<div className="toast"><Check size={17}/>{toast}</div>}
  </div>
}

function ItemCard({item,onClick}:{item:Item,onClick:()=>void}){return <button className="item-card" onClick={onClick}><div className="cover"><img src={item.image} alt={item.name}/><span className="category-pill">{categoryIcons[item.category]} {item.category}</span><span className={`condition ${item.condition==='待修'?'bad':''}`}>{item.condition}</span></div><div className="card-body"><h3>{item.name}</h3><p>{item.meta}</p><div className="tags">{item.tags.map(t=><span key={t}><Tag size={11}/>{t}</span>)}</div><div className="card-footer"><span><Clock3 size={13}/> {item.last==='尚无记录'?'尚无维修记录':`最近 ${item.last}`}</span><b>{item.records} 条履历</b></div></div></button>}

function ItemDetail({item,records,onBack,onAdd}:{item:Item;records:RecordItem[];onBack:()=>void;onAdd:()=>void}){const [tab,setTab]=useState('履历时间线');return <><header className="detail-head"><button className="back" onClick={onBack}>← 返回档案库</button><div className="detail-actions"><button className="icon-btn" title="分享"><Share2 size={18}/></button><button className="secondary" onClick={onAdd}><Plus size={16}/>新增履历</button><button className="icon-btn" title="更多"><MoreHorizontal size={18}/></button></div></header><section className="item-hero"><img src={item.image} alt={item.name}/><div><div className="hero-label">{categoryIcons[item.category]} {item.category} · {item.condition}</div><h1>{item.name}</h1><p>{item.meta}　·　加入于 2023 年</p><div className="tags">{item.tags.map(t=><span key={t}><Tag size={11}/>{t}</span>)}</div></div><div className="hero-stats"><div><span>维修次数</span><b>{records.length}</b></div><div><span>累计花费</span><b>¥{records.reduce((a,r)=>a+r.cost,0)}</b></div></div></section><nav className="tabs">{['履历时间线','损坏部位','照片墙','提醒','统计'].map(t=><button className={tab===t?'active':''} onClick={()=>setTab(t)} key={t}>{t}{t==='履历时间线'&&<small>{records.length}</small>}</button>)}</nav>{tab==='履历时间线'&&<section className="timeline"><div className="timeline-head"><div><h2>维修履历</h2><p>记录这件物品经历的每一次修复与保养</p></div><button className="text-btn"><FileDown size={15}/>导出履历</button></div>{records.length?records.map(r=><article className="record" key={r.id}><div className="record-date"><b>{r.date.slice(5).replace('-','.')}</b><span>{r.date.slice(0,4)}</span></div><div className="record-line"><i></i></div><div className="record-content"><div className="record-top"><span className={`type ${r.type==='保养'?'maintain':''}`}>{r.type}</span><span className="result"><Check size={13}/>{r.result}</span></div><h3>{r.title}</h3><p>{r.body}</p><div className="record-meta"><span><Wrench size={14}/>自己 · {r.createdBy}</span><span><span className="coin">¥</span> 材料与工时 ¥{r.cost}</span></div>{r.photos.length>0&&<div className="mini-photos">{r.photos.map(p=><img src={p} key={p} alt="维修照片"/>)}<span><ImageIcon size={15}/> 查看照片</span></div>}</div></article>):<div className="empty"><BookOpen size={32}/><h3>还没有维修履历</h3><p>把下一次维修记录下来，几年后依然清楚来龙去脉。</p><button className="primary" onClick={onAdd}><Plus size={16}/>新增第一条履历</button></div>}</section>}{tab==='照片墙'&&<PhotoCompare item={item}/>} {tab!=='履历时间线'&&tab!=='照片墙'&&<div className="empty tab-empty"><BookOpen size={32}/><h3>{tab}即将呈现</h3><p>数据结构已经预留，先从新增一条履历开始。</p></div>}</>}

function PhotoCompare({item}:{item:Item}){const [value,setValue]=useState(52);const before='https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=1200&q=85';return <section className="photo-compare"><div className="timeline-head"><div><h2>前后照片对比</h2><p>拖动中间滑块查看维修前后的变化</p></div><span className="compare-badge"><ImageIcon size={14}/> 2 张照片</span></div><div className="compare-frame"><img src={item.image} alt="维修后"/><div className="compare-before" style={{width:`${value}%`}}><img src={before} alt="维修前"/></div><div className="compare-divider" style={{left:`${value}%`}}><span>↔</span></div><input className="compare-range" type="range" min="5" max="95" value={value} onChange={e=>setValue(Number(e.target.value))} aria-label="调整前后照片比例"/></div><div className="compare-labels"><span>维修前 · 2025.08.12</span><span>维修后 · 2025.08.14</span></div></section>}

function Reminders({notify}:{notify:(s:string)=>void}){const [done,setDone]=useState<number[]>([]);const rs=[{id:1,item:'Yamaha FG-180',title:'换弦并上指板油',due:'今天',rule:'每 3 个月',icon:'♫'},{id:2,item:'海鸥 4A 双反',title:'检查遮光海绵状态',due:'3 天后',rule:'每年',icon:'◉'},{id:3,item:'飞利浦 B5X43A 收音机',title:'除尘与电子管检查',due:'2025.09.14',rule:'每 6 个月',icon:'◌'}];return <><header className="topbar"><div><p className="eyebrow">保持物件在最佳状态</p><h1>提醒中心</h1></div><button className="primary" onClick={()=>notify('提醒创建入口已准备') }><Plus size={17}/>新建提醒</button></header><section className="reminder-summary"><div><Bell size={18}/><b>3</b><span>待处理提醒</span></div><div><Check size={18}/><b>8</b><span>本年已完成</span></div><div><CalendarDays size={18}/><b>92%</b><span>按时完成率</span></div></section><div className="reminder-groups"><h2>待处理</h2>{rs.map(r=>done.includes(r.id)?null:<div className="reminder-row" key={r.id}><div className="reminder-icon">{r.icon}</div><div className="reminder-info"><b>{r.title}</b><span>{r.item} · {r.rule}</span></div><div className={`due ${r.due==='今天'?'today':''}`}>{r.due}</div><button className="small-primary" onClick={()=>{setDone([...done,r.id]);notify('提醒已完成，并生成保养履历')}}><Check size={14}/>完成并记录</button><button className="icon-btn" title="更多"><MoreHorizontal size={17}/></button></div>)}</div><div className="reminder-groups"><h2>已完成 <span>本月</span></h2><div className="completed-row"><Check size={16}/><div><b>清洁海鸥 4A 取景器</b><span>2025.08.20 · 林默</span></div><em>已生成履历</em></div></div></>}

function Household({notify}:{notify:(s:string)=>void}){return <><header className="topbar"><div><p className="eyebrow">一起守护家里的老物件</p><h1>家庭成员</h1></div><button className="primary" onClick={()=>notify('邀请码已复制到剪贴板')}><Share2 size={17}/>邀请成员</button></header><section className="household-card"><div className="household-title"><div className="house-icon"><Home size={21}/></div><div><h2>默叔的收藏室</h2><p>创建于 2023 年 4 月 · 共 {5} 件物件</p></div></div><div className="invite"><span>家庭邀请码</span><b>MLCS-8K2P</b><button onClick={()=>notify('邀请码已复制')}><Share2 size={15}/>复制</button></div></section><section className="members"><div className="section-head"><div><h2>成员</h2><span>3 位成员</span></div></div>{[['林默','我','所有者','林'],['陈叔','','编辑者','陈'],['林小满','','查看者','满']].map((m,i)=><div className="member-row" key={m[0]}><div className="avatar">{m[3]}</div><div><b>{m[0]} {m[1]&&<small>{m[1]}</small>}</b><span>最近活跃于 {i===0?'刚刚':i===1?'昨天':'3 天前'}</span></div><em className={i===0?'owner':''}>{m[2]}</em><button className="icon-btn" title="更多"><MoreHorizontal size={17}/></button></div>)}</section></>}
function SettingsPage({notify}:{notify:(s:string)=>void}){return <><header className="topbar"><div><p className="eyebrow">偏好与数据</p><h1>设置</h1></div></header><section className="settings"><div className="setting-group"><h2>通知偏好</h2><label><span><Bell size={17}/><b>到期提醒</b><small>在提醒到期时发送站内通知</small></span><input type="checkbox" defaultChecked/></label><label><span><Share2 size={17}/><b>邮件通知</b><small>同时发送提醒和邀请邮件</small></span><input type="checkbox" defaultChecked/></label></div><div className="setting-group"><h2>数据</h2><button className="setting-action" onClick={()=>notify('正在准备全量 JSON 导出')}><FileDown size={17}/><span><b>导出全部数据</b><small>JSON 数据与附件压缩包</small></span><ChevronRight size={17}/></button><button className="setting-action" onClick={()=>notify('单物件 PDF 导出已开始')}><BookOpen size={17}/><span><b>导出物件履历 PDF</b><small>选择物件后生成含照片的 PDF</small></span><ChevronRight size={17}/></button></div></section></>}
function NewItemModal({onClose,onCreate}:{onClose:()=>void;onCreate:(n:string,c:Category)=>void}){const [name,setName]=useState('');const [cat,setCat]=useState<Category>('相机');return <div className="overlay"><div className="modal"><div className="modal-head"><div><span className="eyebrow">建立新档案</span><h2>添加物件</h2></div><button className="icon-btn" onClick={onClose}><X size={18}/></button></div><label className="field">物件名称<input autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder="例如：海鸥 4A 双反"/></label><label className="field">类别<select value={cat} onChange={e=>setCat(e.target.value as Category)}>{(['相机','收音机','家具','乐器','其他'] as Category[]).map(c=><option key={c}>{c}</option>)}</select></label><div className="cover-drop"><Camera size={24}/><span>添加封面照片</span><small>可稍后补充</small></div><div className="modal-actions"><button className="secondary" onClick={onClose}>取消</button><button className="primary" disabled={!name.trim()} onClick={()=>onCreate(name.trim(),cat)}><Plus size={16}/>创建档案</button></div></div></div>}
function NewRecordModal({onClose,onCreate}:{onClose:()=>void;onCreate:(t:string)=>void}){const [title,setTitle]=useState('');return <div className="overlay"><div className="modal"><div className="modal-head"><div><span className="eyebrow">新增一条履历</span><h2>记录这次维修</h2></div><button className="icon-btn" onClick={onClose}><X size={18}/></button></div><label className="field">标题<input autoFocus value={title} onChange={e=>setTitle(e.target.value)} placeholder="例如：更换取景器遮光海绵"/></label><div className="quick-fields"><label className="field">类型<select><option>维修</option><option>保养</option><option>修复</option><option>检查</option></select></label><label className="field">结果<select><option>草稿</option><option>已修复</option><option>观察中</option></select></label></div><label className="field">诊断<textarea placeholder="描述发现了什么问题…" rows={3}/></label><div className="modal-actions"><button className="secondary" onClick={onClose}>保存草稿</button><button className="primary" disabled={!title.trim()} onClick={()=>onCreate(title.trim())}><Check size={16}/>保存履历</button></div></div></div>}
createRoot(document.getElementById('root')!).render(<App/>);
